### ISSUE TITLE
Unexpected blank page after committing to a product

### ISSUE THREAD

**Issue by levalleux-ludo** [bosonprotocol/interface#1032]
- connect the user wallet
- open a product details page
- commit to the product
- when the transaction is completed, the ProductCreateSuccess is appearing for a very short time
- then, it disappear and the page is totally blank
![image](https://github.com/bosonprotocol/interface/assets/7184124/95b601cc-4322-41c5-962e-449e37a3d7f6)
- click Refresh
- the product page is loading again, but the wallet has been disconnected
![image](https://github.com/bosonprotocol/interface/assets/7184124/81dd81cb-11c1-4d35-902b-611ab9db8a35)

**Comment by levalleux-ludo** [comment]
Here are some errors in the console logs:
`react-dom.development.js:16572 Uncaught Error: Should have a queue. This is likely a bug in React. Please file an issue.
    at updateReducer (react-dom.development.js:16572:1)
    at updateState (react-dom.development.js:17004:1)
    at Object.useState (react-dom.development.js:17915:1)
    at useState (react.development.js:1622:1)
    at useIsWindowVisible (useIsWindowVisible.ts:15:1)
    at ListsUpdater (updater.ts:21:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at HTMLUnknownElement.sentryWrapped (helpers.ts:98:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
updateReducer @ react-dom.development.js:16572
updateState @ react-dom.development.js:17004
useState @ react-dom.development.js:17915
useState @ react.development.js:1622
useIsWindowVisible @ useIsWindowVisible.ts:15
ListsUpdater @ updater.ts:21
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19588
beginWork @ react-dom.development.js:21601
callCallback @ react-dom.development.js:4164
sentryWrapped @ helpers.ts:98
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
`

`Uncaught Error: Should have a queue. This is likely a bug in React. Please file an issue.
    at updateReducer (react-dom.development.js:16572:1)
    at updateState (react-dom.development.js:17004:1)
    at Object.useState (react-dom.development.js:17915:1)
    at useState (react.development.js:1622:1)
    at useIsWindowVisible (useIsWindowVisible.ts:15:1)
    at ListsUpdater (updater.ts:21:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at HTMLUnknownElement.sentryWrapped (helpers.ts:98:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:25750:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)﻿﻿﻿`

`The above error occurred in the <ListsUpdater> component:

    at ListsUpdater (http://localhost:3333/static/js/bundle.js:161830:93)
    at Updaters (http://localhost:3333/static/js/bundle.js:162102:3)
    at WalletConnectionProvider (http://localhost:3333/static/js/bundle.js:145262:3)
    at QueryClientProvider (http://localhost:3333/static/js/bundle.js:518794:21)
    at UserProvider (http://localhost:3333/static/js/bundle.js:130728:3)
    at InnerMagicProvider (http://localhost:3333/static/js/bundle.js:130649:3)
    at MagicProvider (http://localhost:3333/static/js/bundle.js:130635:3)
    at InnerConfigProvider (http://localhost:3333/static/js/bundle.js:124715:3)
    at EnvironmentProvider (http://localhost:3333/static/js/bundle.js:127407:3)
    at ConfigProvider (http://localhost:3333/static/js/bundle.js:124703:3)
    at Provider (http://localhost:3333/static/js/bundle.js:519476:3)
    at CommitWidgetProviders (http://localhost:3333/static/js/bundle.js:145615:3)
    at div
    at O (http://localhost:3333/static/js/bundle.js:559060:6)
    at ExternalCommitDetailView (http://localhost:3333/static/js/bundle.js:131819:14)
    at CommitDetailWidget (http://localhost:3333/static/js/src_components_detail_DetailWidget_CommitDetailWidget_tsx.chunk.js:805:3)
    at div
    at div
    at O (http://localhost:3333/static/js/bundle.js:559060:6)
    at div
    at O (http://localhost:3333/static/js/bundle.js:559060:6)
    at div
    at O (http://localhost:3333/static/js/bundle.js:559060:6)
    at ProductDetail (http://localhost:3333/static/js/src_pages_products_ProductDetail_tsx.chunk.js:343:67)
    at div
    at O (http://localhost:3333/static/js/bundle.js:559060:6)
    at Layout (http://localhost:3333/static/js/bundle.js:19481:3)
    at http://localhost:3333/static/js/bundle.js:3846:3
    at DappView (http://localhost:3333/static/js/bundle.js:3417:12)
    at AppView (http://localhost:3333/static/js/bundle.js:3321:12)
    at div
    at O (http://localhost:3333/static/js/bundle.js:559060:6)
    at ModalProvider (http://localhost:3333/static/js/bundle.js:20879:3)
    at ChatProvider (http://localhost:3333/static/js/bundle.js:85106:3)
    at tt (http://localhost:3333/static/js/bundle.js:558977:56)
    at App (http://localhost:3333/static/js/bundle.js:3713:3)
    at Suspense
    at SuspenseRoute (http://localhost:3333/static/js/bundle.js:88128:3)
    at RenderedRoute (http://localhost:3333/static/js/bundle.js:525842:5)
    at Routes (http://localhost:3333/static/js/bundle.js:526474:5)
    at SentryRoutes (http://localhost:3333/static/js/bundle.js:242502:22)
    at SentryProvider (http://localhost:3333/static/js/bundle.js:3230:3)
    at Router (http://localhost:3333/static/js/bundle.js:526412:15)
    at HashRouter (http://localhost:3333/static/js/bundle.js:524553:5)
    at AppRouter (http://localhost:3333/static/js/bundle.js:87946:88)
    at FiatLinkProvider (http://localhost:3333/static/js/bundle.js:15397:3)
    at ConvertionRateProvider (http://localhost:3333/static/js/bundle.js:4517:3)
    at ConvertionRateProviderWrapper (http://localhost:3333/static/js/bundle.js:4498:3)
    at CoreSDKProvider (http://localhost:3333/static/js/bundle.js:5058:3)
    at QueryClientProvider (http://localhost:3333/static/js/bundle.js:518794:21)
    at BlockNumberProvider (http://localhost:3333/static/js/bundle.js:77147:3)
    at ApolloProvider (http://localhost:3333/static/js/bundle.js:607333:19)
    at SyncCurrentConfigId (http://localhost:3333/static/js/bundle.js:4162:3)
    at UserProvider (http://localhost:3333/static/js/bundle.js:130728:3)
    at InnerMagicProvider (http://localhost:3333/static/js/bundle.js:130649:3)
    at MagicProvider (http://localhost:3333/static/js/bundle.js:20085:3)
    at ConfigProvider (http://localhost:3333/static/js/bundle.js:4184:3)
    at Web3ReactProvider (http://localhost:3333/static/js/bundle.js:577880:3)
    at Web3Provider (http://localhost:3333/static/js/bundle.js:18908:3)
    at Provider (http://localhost:3333/static/js/bundle.js:519476:3)
    at StrictMode (http://localhost:3333/static/js/bundle.js:56067:3)`
